language: java

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2

script: mvn clean package

env:
  global:
    - secure: "EVKYbjPcAqu8yeT7AWiyNVSEpJeHrmngHJ/BukHiVbUCdSagu0YFneJVgGZyoPD61OM7Qd4kcAflGFIrKThbJzsH/wrIatbnZmnbugRlCBEVJ0sulooC/bGbZCUXBZkbyiHvOoGmChjbpeZJtc5KQ+zmCn7TuzmNSx1c8klnGUWTeno3hMAxf9QQ81uciUkga3XAzJhtil3gmpc2aao2MIwR8PzSts+Jw1WEBWOBGfADuNGvf5gUFDAF7KF/JveuyarAk1czExxEOVS5/ZydxuZNVlGKMSqQF98Vp1oBh100fLDUgPRDnjpcNwb4E214C2mqCeeuXctH9xfO9hpStrAo9o8mARP79ivhv+cAdExn5eF5C8Fv/X6N1vJbYAfTUj0U/35LOT+7+Nhhhpyu8kFIe4uDaDtOpMFKbbDKmqSzIS0tEG861Jhy7FgWSjDkATMqSPUlYHXYnQuYjO7poZYM3Q1suBFZN9XNbMAd7uoHID99BJmOCunDR+s8tXr6cNC2Cv9HSO3MkJsjGM+MT1G19q3qItzAeG8gsHGzKcs72g6q7vhex6RsksrV371TkixnZ4rpi4Jt7NtrsFQtz+F+gnn90nOn+QL0Y9hSULxx7KuKlBEDfhAuR5r/pIG/ZrTj6XM1Z53Xsd3EMBkAM5A+s0+crAAQe926JFzYKWI="
    - secure: "OlUWD4/6vF1nc5t7Fl0vhknc96JJoAngjByyWSWzKCMKnlfCxHhLoVksFFw11fcLRZRCBj/6FJAezzd6lgU2y7GdgKWWLEpgTWrXM6EdNbClNxT6dcW6UzgegqsRbfx1j6Gw2Dh+2Y3eZ71x9f2lFJGnOBSSsVPdPAWoRJ8dKc0OABiny5VcVC7x7YLNuAPNOzXI69Ozd57wLB1TufMM0w6VpjI7rgdebPHyIc2h81Jjedt0YQAJkSSLMS4UUp218hFeSDDF2WrLpf3wT396p7xYlknPiSpt0NIzo9iCzxcQxaQn2qOy7Jx7fzlnrxNy3DhFa5wDeUDlk9BRdsNCGkSnik29c0JS2Bn/D1SNWuehaJ8G1j9oZVfRTNtddEMTwgaqykR1oELkbxXPlxR5v9DVhl2B7FMHNopVPsLcgYCwVUu1cGiT4YFpxSAaGpVMiq9jNYoLgLnWLio5tvsAkv1tgxPhLbQuBmlx1lDMy3c79ySlJ0fm/s71yj6bLo2ezZ0vbcIXBh3xhLchBzE+kV2SO6c2mcHLlHEsmi+HkDFUQiUp9tARmZQ1e/Yj7/jhzRBqiYST2vuD6F1M7qgbOctHDeg5smuxHtuJqH722b91BEhhKX/t8Om1kuaiFJUTvdPBXztvdaLuAb19fn4MeJ+JA8uQT3vqoWLIaxFvACk="

branches:
  only:
    - master
    - /^release.*$/